# Generated by Django 5.2.1 on 2025-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_categoria_formapagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='dados_api_cnpj',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
